---
layout: post
title: 前端进阶知识（87）———— ES6 Generator 函数
date: 2017-09-18
tags: [ES6]
---

ES6 提供了一中异步编程的解决方法，它就是Generator。

# Introduction

## the basic concept of Generator

从英文的角度直译过来，Generator的意思是“发生器”。这个函数内部封装了多个状态。

直接执行它，会返回一个Iterator对象，之前讲过Iterator就是一个遍历接口，那么意味着，它可以被for...of遍历。

作为一个函数，它在函数名之间有一个*号（看到这个星号有种莫名的恐惧感，C++中的指针。。。），还有就是，函数内部使用yield表达式，定义不同的内部状态（yield：产出）

    function * hh(){
        yield " hello ";
        yield " world ";
        return  " ending ";
    }
    var hhn = hh();

每个yield代表一个状态，那么这里一共有三个状态：hello，world，return语句（结束）。

当Generator函数被调用之后，不会执行，返回的也不是函数执行的结果。而是一个指向内部状态的指针对象，就是之前讲过的Iterator遍历器对象。

之后我们就可以使用next方法，遍历每个状态。每次调用next，都会把指针指向下一个状态。

    hhn.next()
    // { value: 'hello', done: false }

    hhn.next()
    // { value: 'world', done: false }

    hhn.next()
    // { value: 'ending', done: true }

    hhn.next()
    // { value: undefined, done: true }

## about the yield expression

由于Generator函数返回的遍历对象，只有调用next方法才会遍历下一个内部状态，所以相当于提供了一种可以暂停执行的函数。yield表达式就是暂停的标志。

next方法的具体逻辑：

（1）遇到yield表达式，就暂停执行后面的操作，并将紧跟在yield后面的那个表达式的值，作为返回的对象的value属性值。

（2）下一次调用next方法时，再继续往下执行，直到遇到下一个yield表达式。

（3）如果没有再遇到新的yield表达式，就一直运行到函数结束，直到return语句为止，并将return语句后面的表达式的值，作为返回的对象的value属性值。

（4）如果该函数没有return语句，则返回的对象的value属性值为undefined。

需要注意的是，yield表达式后面的表达式，只有当调用next方法、内部指针指向该语句时才会执行。还有一点要注意的是，yield表达式只能用在Generator函数里面，用在其他地方都会报错。

## the relationship with Generator

任意一个对象的Symbol.iterator方法，等于该对象的遍历器生成函数，调用该函数会返回该对象的一个遍历器对象。

由于 Generator 函数就是遍历器生成函数，因此可以把 Generator 赋值给对象的Symbol.iterator属性，从而使得该对象具有 Iterator 接口。

    var myIterable = {};
    myIterable[Symbol.iterator] = function* () {
    yield 1;
    yield 2;
    yield 3;
    };

    [...myIterable] // [1, 2, 3]
    function * gen(){
    yield hh()
    }
    function hh(){
            console.log(33);
        }
    var ha = gen();
    ha.next()//33

Generator 函数赋值给Symbol.iterator属性，从而使得myIterable对象具有了 Iterator 接口，可以被...运算符遍历了.

### next parameter

yield表达式本身没有返回值，next方法可以自带一个参数，该参数就会被当做上一个yield表达式的返回值。

### for...of循环

for...of循环可以自动遍历Generator函数时生成的Iterator对象，且这个时候不需要调用next方法。

    function *foo() {
    yield 1;
    yield 2;
    yield 3;
    yield 4;
    yield 5;
    return 6;
    }

    for (let v of foo()) {
    console.log(v);
    }
    // 1 2 3 4 5

上面代码使用for...of循环，依次显示5个yield表达式的值。这里需要注意，一旦next方法的返回对象的done属性为true，for...of循环就会中止，且不包含该返回对象，所以上面代码的return语句返回的6，不包括在for...of循环之中。

### Generator.prototype.throw()

Generator函数返回的遍历对象，都哟哟一个throw方法，可以在函数体外抛出错误，然后再Generator函数体内捕获。

    var g = function* () {
    try {
        yield;
    } catch (e) {
        console.log('内部捕获', e);
    }
    };

    var i = g();
    i.next();

    try {
    i.throw('a');
    i.throw('b');
    } catch (e) {
    console.log('外部捕获', e);
    }

上面代码中，遍历器对象i连续抛出两个错误。第一个错误被 Generator 函数体内的catch语句捕获。i第二次抛出错误，由于 Generator 函数内部的catch语句已经执行过了，不会再捕捉到这个错误了，所以这个错误就被抛出了 Generator 函数体，被函数体外的catch语句捕获。

### Generator.prototype.return()

Generator 函数返回的遍历器对象，还有一个return方法，可以返回给定的值，并且终结遍历 Generator 函数。

    function* gen() {
    yield 1;
    yield 2;
    yield 3;
    }

    var g = gen();

    g.next()        // { value: 1, done: false }
    g.return('foo') // { value: "foo", done: true }
    g.next()        // { value: undefined, done: true }

上面代码中，遍历器对象g调用return方法后，返回值的value属性就是return方法的参数foo。并且，Generator函数的遍历就终止了，返回值的done属性为true，以后再调用next方法，done属性总是返回true。

那么这部分的内容就先讲到这.晚安！！